### ISSUE TITLE
Debug works incorrectly 

### ISSUE THREAD

**Issue by sobolevn** [octref/veturpack#13]
Hi, I have a problem with `vscode` debugging.

Steps to reproduce:
1. clone `master` branch
2. open `vscode`
3. add `<button @click="hello">Hello</button>` to template in `Component.vue`
4. set breakpoint inside `hello()` method, also set some breakpoints inside `store/index.js`
5. run `yarn` and `yarn dev` in embed terminal
6. run debuuger
7. click `Hello` button

I can illustrate what actually happens:

 
![2018-05-09 20 15 10](https://user-images.githubusercontent.com/4660275/39829156-289e2cc2-53c6-11e8-8773-723de4c63689.png)
![2018-05-09 20 13 59](https://user-images.githubusercontent.com/4660275/39829158-28cd0f10-53c6-11e8-81f4-3c68d9483cbb.png)

And I had no luck in reaching these breakpoints.

However, it is possible to debug `store` with no problems.
![2018-05-09 20 20 08](https://user-images.githubusercontent.com/4660275/39829215-62fef612-53c6-11e8-986a-a1e51ae9778e.png)

**Comment by sobolevn** [comment]
Original issue: https://github.com/vuejs/vue-loader/issues/1163

**Comment by sobolevn** [comment]
After reading this comment https://github.com/vuejs/vue-loader/issues/1163#issuecomment-384712864
I have tried to update `babel-core` to `6.26.3`, but it still does not work.

**Comment by octref** [comment]
Yes, the issue is really a sourcemap issue. Until https://github.com/vuejs/vue-loader/issues/1163 is completely solved nothing I can do here.
