### ISSUE TITLE
Strange menu display when using ale

### ISSUE THREAD

**Issue by npearson72** [octref/veturpack#14]
When using https://github.com/w0rp/ale the auto complete menu shifts and displays a duplicate.

See animated gif:

![kapture 2019-01-08 at 23 34 22](https://user-images.githubusercontent.com/1323414/50861407-3b79a100-13a1-11e9-88cb-29d4c5f21169.gif)

**Comment by octref** [comment]
That should be an issue for ale, not for this repo.

**Comment by npearson72** [comment]
Pardon me. I had multiple windows opened and posted this into the wrong repo.
