### ISSUE TITLE
Emmet expansion not working

### ISSUE THREAD

**Issue by bobmoff** [octref/veturpack#2]
* Installed VS Code
* cloned this repo, 
* yarn
* yarn dev. 

Emmet doesnt work in templates or styles. Still works in regular .html files though.

I am running on macOS Sierra 10.12.5 (16F73).

Not sure what could be wrong. VSCode says everything is fine.

**Comment by octref** [comment]
This is a known issue and we are working to fix it.
https://github.com/vuejs/vetur/issues/232

**Comment by octref** [comment]
You can upgrade to latest version and everything should work without any specific emmet settings.
