### ISSUE TITLE
Vue properties cannot be typed and causing errors

### ISSUE THREAD

**Issue by jank84** [octref/veturpack#3]
![image](https://user-images.githubusercontent.com/3295430/29405274-bff511d0-833d-11e7-8f73-06befc19c93a.png)

Jsdoc typing doesn't help ether, because ```this``` in ```count ()``` is a anonymous function != ```data: function ()```

```
(property) (Anonymous function).testNumberVar
```

**Comment by octref** [comment]
`// @ts-check` will only work ok with an updated TS definition, see https://github.com/Microsoft/TypeScript-Vue-Starter

The updated PR for the TS definition is not yet merged on Vue side yet, too: https://github.com/vuejs/vue/pull/6391
