### ISSUE TITLE
emmet cannot expand custom single word tags

### ISSUE THREAD

**Issue by bobmoff** [octref/veturpack#8]
i cloned the repo and am trying out emmet.

as long as it is a recognized html tag, or it is a custom two-word tag it works, but not when i want to expand my custom component called spinner. i get "no suggestion". if i try my-spinner, it works. 

is this intentional, and if so - why ?

**Comment by octref** [comment]
CC @ramya-rao-a because she's the author of vscode-emmet-helper that Vetur uses.

**Comment by ramya-rao-a** [comment]
See the below from https://code.visualstudio.com/docs/editor/emmet

<img width="778" alt="screen shot 2017-12-05 at 6 26 07 pm" src="https://user-images.githubusercontent.com/16890566/33641309-d35c0960-d9e9-11e7-8530-ed51931fef18.png">

**Comment by bobmoff** [comment]
ooooh yes, thanks!
